permalink   : /:title/
markdown    : kramdown
highlighter : rouge

gems: [jekyll-paginate]
paginate: 4 #6
comments: true
paginate_path: "/page/:num"

baseurl: "" # change to empty string ""
domain_name: by0ute.github.com
# google_analytics: UA-52446115-1

source:      source
destination: _site
port: 9001

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: By0ute
title: ++ By0ute.io ++ 
description: "Software dev + TD life + post-prod code"
meta_description: "Software Developer, TD, Technical Director, Post production code"
meta_keywords: "site, website, code, c++, python, mel, td, post prod, cg, studio"
url: http://by0ute.github.com
production_url: http://by0ute.github.com
repo: https://github.com/By0ute/by0ute.github.io
disqus_shortname: byouteio
rss_path: source/
author:
  name      : Byoute
  image     : /assets/images/pixellou.jpg
  email     : mail@byoute.io
  url       : http://carolinebeyne.com
  twitter   : http://twitter.com/CaroByoute
  github    : http://github.com/By0ute
  linkedin  : http://linkedin.com/in/carolinebeyne
  bio       : "Software developer officiating as TD in a post prod studio"

# thought
# thought:
#   text: I have no special talent. I am only passionately curious.
#   author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  # cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
