
# Syntax highlighting
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           /:title
relative_permalinks: false

# Setup
timezone:            Europe/Paris # eg. Asia/Kathmandu
locale:              fr_fr # eg. en_us
name:				         Byoute.io
title:               Byoute ++
tagline:             'tagline'
description:         Byoute's pieces of code
url:                 http://by0ute.github.io
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                /assets/images/pixellou.jpg # /assets/img/icon.png [best 300px X 300px]
disqus:              byouteio # get it on https://disqus.com/admin/

author:
  name:              Byoute
  url:               http://by0ute.github.io/about
  facebook:          username
  twitter:           CaroByoute
  google_plus:       username
  linkedin:          carolinebeyne
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
